name: Generate Android APK & AAB and publish release on Github

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  prepare_tools:
    name: Prepare tools to generate the APK & AAB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Create site-config.js
        run: "echo $SITE_CONFIG > src/configs/site-config.js"
        env:
          SITE_CONFIG: ${{ secrets.SITE_CONFIG }}

      - name: Build UI
        run: npm install -g @ionic/cli yarn && yarn install && yarn build

      - name: Prepare Android
        run: npx cap add android && npx cap sync && yarn android:post-install && yarn resources

      - name: Get release tag version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Update APK Version Number
        run: sed -i 's|versionName "1.0"|versionName "${{ steps.get_version.outputs.VERSION }}"|g' android/app/build.gradle && sed -i 's|versionName "v|versionName "|g' android/app/build.gradle

      - name: Prepare Gradle
        run: cd android && chmod +x ./gradlew && cd ..

      - name: Copy generated assets from Ionic to Capacitor Android platform
        run: npx cap copy android && npx cap update android

      - name: Build Android APK
        run: cd android && ./gradlew assembleRelease && cd ..

      - name: Sign APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "29.0.2"

      - name: Rename signed APK
        run: mv android/app/build/outputs/apk/release/app-release-unsigned-signed.apk android/app/build/outputs/apk/release/app-release-signed.apk

      - name: Build Android (AAB)
        run: cd android && ./gradlew bundleRelease && cd ..

      - name: Sign AAB
        id: sign_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "29.0.2"

      - name: List aab files
        run: ls android/app/build/outputs/bundle/release/

      - name: Uploading Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: |
            android/app/build/outputs/apk/release/app-release-signed.apk
            android/app/build/outputs/bundle/release/app-release.aab

      - name: Uploading to GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            android/app/build/outputs/apk/release/app-release-signed.apk
            android/app/build/outputs/bundle/release/app-release.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
